export const dashboardTokens = {
  colorPrimary: '#6366f1',
  colorSuccess: '#10b981',
  colorWarning: '#f59e0b',
  colorError: '#ef4444',
  colorInfo: '#3b82f6',
  colorTextBase: '#1f2937',
  colorBgBase: '#fafbfc',
  colorPrimaryBg: '#eef2ff',
  colorPrimaryBgHover: '#e0e7ff',
  colorPrimaryBorder: '#c7d2fe',
  colorPrimaryBorderHover: '#a5b4fc',
  colorPrimaryHover: '#4f46e5',
  colorPrimaryActive: '#4338ca',
  colorPrimaryText: '#6366f1',
  colorPrimaryTextHover: '#4f46e5',
  colorPrimaryTextActive: '#4338ca',
  colorSuccessBg: '#ecfdf5',
  colorSuccessBgHover: '#d1fae5',
  colorSuccessBorder: '#a7f3d0',
  colorSuccessBorderHover: '#6ee7b7',
  colorSuccessHover: '#059669',
  colorSuccessActive: '#047857',
  colorSuccessText: '#10b981',
  colorSuccessTextHover: '#059669',
  colorSuccessTextActive: '#047857',
  colorWarningBg: '#fffbeb',
  colorWarningBgHover: '#fef3c7',
  colorWarningBorder: '#fcd34d',
  colorWarningBorderHover: '#fbbf24',
  colorWarningHover: '#d97706',
  colorWarningActive: '#b45309',
  colorWarningText: '#f59e0b',
  colorWarningTextHover: '#d97706',
  colorWarningTextActive: '#b45309',
  colorErrorBg: '#fef2f2',
  colorErrorBgHover: '#fee2e2',
  colorErrorBorder: '#fca5a5',
  colorErrorBorderHover: '#f87171',
  colorErrorHover: '#dc2626',
  colorErrorActive: '#b91c1c',
  colorErrorText: '#ef4444',
  colorErrorTextHover: '#dc2626',
  colorErrorTextActive: '#b91c1c',
  colorInfoBg: '#eff6ff',
  colorInfoBgHover: '#dbeafe',
  colorInfoBorder: '#bfdbfe',
  colorInfoBorderHover: '#93c5fd',
  colorInfoHover: '#2563eb',
  colorInfoActive: '#1d4ed8',
  colorInfoText: '#3b82f6',
  colorInfoTextHover: '#2563eb',
  colorInfoTextActive: '#1d4ed8',
  colorText: 'rgba(31, 41, 55, 0.88)',
  colorTextSecondary: 'rgba(31, 41, 55, 0.65)',
  colorTextTertiary: 'rgba(31, 41, 55, 0.45)',
  colorTextQuaternary: 'rgba(31, 41, 55, 0.25)',
  colorTextDisabled: 'rgba(31, 41, 55, 0.25)',
  colorBgContainer: '#ffffff',
  colorBgElevated: '#ffffff',
  colorBgLayout: '#f3f4f6',
  colorBgSpotlight: 'rgba(31, 41, 55, 0.85)',
  colorBgMask: 'rgba(31, 41, 55, 0.45)',
  colorBorder: '#e5e7eb',
  colorBorderSecondary: '#f3f4f6',
  borderRadius: 12,
  borderRadiusXS: 4,
  borderRadiusSM: 8,
  borderRadiusLG: 16,
  padding: 20,
  paddingSM: 16,
  paddingLG: 28,
  margin: 20,
  marginSM: 16,
  marginLG: 28,
  boxShadow: '0 4px 12px 0 rgba(0, 0, 0, 0.05)',
  boxShadowSecondary: '0 8px 24px 0 rgba(0, 0, 0, 0.08)',
} as const

export const statusTokens = {
  aplicada: {
    text: dashboardTokens.colorInfoText,
    bg: dashboardTokens.colorInfoBg,
    border: dashboardTokens.colorInfoBorder,
  },
  entrevista: {
    text: dashboardTokens.colorSuccessText,
    bg: dashboardTokens.colorSuccessBg,
    border: dashboardTokens.colorSuccessBorder,
  },
  processo: {
    text: dashboardTokens.colorWarningText,
    bg: dashboardTokens.colorWarningBg,
    border: dashboardTokens.colorWarningBorder,
  },
  recusada: {
    text: dashboardTokens.colorErrorText,
    bg: dashboardTokens.colorErrorBg,
    border: dashboardTokens.colorErrorBorder,
  },
} as const

export type DashboardStatus = keyof typeof statusTokens
