export const dashboardTokens = {
  colorPrimary: '#F1873E',
  colorPrimaryBg: '#FFF1E5',
  colorPrimaryBgHover: '#FFE0CA',
  colorPrimaryBorder: '#F8BA92',
  colorPrimaryBorderHover: '#F39A5C',
  colorPrimaryHover: '#DE7430',
  colorPrimaryActive: '#BE5F21',
  colorPrimaryText: '#F1873E',
  colorPrimaryTextHover: '#DE7430',
  colorPrimaryTextActive: '#BE5F21',
  colorOnPrimary: '#FFF8F2',

  colorSuccess: '#63BFAF',
  colorSuccessBg: '#E8FAF6',
  colorSuccessBgHover: '#D7F5EE',
  colorSuccessBorder: '#A3E3D6',
  colorSuccessBorderHover: '#7BD2C1',
  colorSuccessHover: '#4DAE9E',
  colorSuccessActive: '#3D9184',
  colorSuccessText: '#2E9182',
  colorSuccessTextHover: '#24776A',
  colorSuccessTextActive: '#1C6055',

  colorWarning: '#C69B5A',
  colorWarningBg: '#FFF7E7',
  colorWarningBgHover: '#FDEFCB',
  colorWarningBorder: '#EAC887',
  colorWarningBorderHover: '#DDB160',
  colorWarningHover: '#B88740',
  colorWarningActive: '#9A6E31',
  colorWarningText: '#9F702F',
  colorWarningTextHover: '#85591F',
  colorWarningTextActive: '#6A4514',

  colorError: '#E36352',
  colorErrorBg: '#FFF0ED',
  colorErrorBgHover: '#FFDCD6',
  colorErrorBorder: '#F5B0A7',
  colorErrorBorderHover: '#EA8477',
  colorErrorHover: '#CC4E3D',
  colorErrorActive: '#AE3E31',
  colorErrorText: '#C84D3D',
  colorErrorTextHover: '#A63D30',
  colorErrorTextActive: '#823125',

  colorInfo: '#6D8CFF',
  colorInfoBg: '#EEF2FF',
  colorInfoBgHover: '#E0E7FF',
  colorInfoBorder: '#C8D2FF',
  colorInfoBorderHover: '#AAB9FF',
  colorInfoHover: '#5675E5',
  colorInfoActive: '#435CC2',
  colorInfoText: '#5675E5',
  colorInfoTextHover: '#425DBE',
  colorInfoTextActive: '#34489A',

  colorTextBase: '#102033',
  colorText: 'rgba(16, 32, 51, 0.90)',
  colorTextSecondary: 'rgba(16, 32, 51, 0.66)',
  colorTextTertiary: 'rgba(16, 32, 51, 0.48)',
  colorTextQuaternary: 'rgba(16, 32, 51, 0.28)',
  colorTextDisabled: 'rgba(16, 32, 51, 0.22)',

  colorBgBase: '#F5EFE6',
  colorBgContainer: '#FFFDFC',
  colorBgElevated: '#FFFFFF',
  colorBgLayout: '#EDE3D4',
  colorBgSpotlight: 'rgba(12, 24, 39, 0.88)',
  colorBgMask: 'rgba(12, 24, 39, 0.48)',
  colorBgCanvasDark: '#162131',
  colorBgCanvasDarkAlt: '#1E2B40',
  colorBgAccentSoft: '#FFF7F1',

  colorBorder: '#E2D7C7',
  colorBorderSecondary: '#F2EBE2',

  borderRadius: 18,
  borderRadiusXS: 6,
  borderRadiusSM: 12,
  borderRadiusLG: 24,
  padding: 24,
  paddingSM: 16,
  paddingLG: 32,
  margin: 24,
  marginSM: 16,
  marginLG: 32,
  boxShadow: '0 10px 32px rgba(18, 32, 49, 0.08)',
  boxShadowSecondary: '0 22px 60px rgba(18, 32, 49, 0.14)',

  fontFamilyBody: "'Manrope', 'Segoe UI', sans-serif",
  fontFamilyDisplay: "'Sora', 'Segoe UI', sans-serif",
} as const

export const statusTokens = {
  aplicada: {
    text: dashboardTokens.colorPrimaryText,
    bg: dashboardTokens.colorPrimaryBg,
    border: dashboardTokens.colorPrimaryBorder,
    dot: dashboardTokens.colorPrimary,
  },
  entrevista: {
    text: dashboardTokens.colorSuccessText,
    bg: dashboardTokens.colorSuccessBg,
    border: dashboardTokens.colorSuccessBorder,
    dot: dashboardTokens.colorSuccess,
  },
  processo: {
    text: dashboardTokens.colorInfoText,
    bg: dashboardTokens.colorInfoBg,
    border: dashboardTokens.colorInfoBorder,
    dot: dashboardTokens.colorInfo,
  },
  recusada: {
    text: dashboardTokens.colorErrorText,
    bg: dashboardTokens.colorErrorBg,
    border: dashboardTokens.colorErrorBorder,
    dot: dashboardTokens.colorError,
  },
} as const

export type DashboardStatus = keyof typeof statusTokens
